### ISSUE TITLE
Broken title on mobile

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-gutenberg#32]
I've noticed that on mobile (or very narrow windows) one of bottom sections ("New to WordPress. No problem") gets broken, resulting in something like this:

<img src="https://user-images.githubusercontent.com/4933/165271836-f57c77d7-f858-4fc2-bc9f-2a8726b661df.jpeg" width="400" />

**Comment by StevenDufresne** [comment]
Changes made in #33 coincidentally fixed this line-height issue.
