### ISSUE TITLE
Slightly horizontal scroll on mobile

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-gutenberg#33]
On mobile (tested on macOS Chrome) there's a slightly horizontal scroll:

https://user-images.githubusercontent.com/4933/165273232-691a1a6e-74d4-40c7-acc7-2cb2e1ef750e.MP4

**Comment by StevenDufresne** [comment]
@javierarce Thanks for opening the issue. 

I implemented the change in e8c2e780d33185daca73917c8db9364311a1fc7c. Reopen if you still see the issue :).
