### ISSUE TITLE
Consider giving stacked buttons priority.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-gutenberg#38]
> The double button/CTA, have we considered a way to give them a prioritiy in style?

### Screenshot
<img width="300px" src="https://d.pr/f/YNupk9.png">

**Comment by beafialho** [comment]
It may make sense to fill the "Block Pattern Directory" with the blue color.

**Comment by StevenDufresne** [comment]
Okay, I filled it in. We can adjust after this goes live if we want.
