### ISSUE TITLE
Consider more diversity in patterns image

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-gutenberg#39]
> Would it make sense to have more diverse patterns here avoiding looking like from the same vibe, color scheme, layout, fonts?

### Screenshots
<img width="400px" src="https://d.pr/f/jxn3nB.png">

**Comment by beafialho** [comment]
Let's replace it with [this](cloudup.com/clX-bw5n7YN) screenshot.

**Comment by StevenDufresne** [comment]
Updated. Thanks.
