### ISSUE TITLE
Icon alignments seem off.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-gutenberg#40]
>  This might be related to scaling the current icons (can we also make sure we are using the latest?), but these seem misaligned in stroke.

### Screenshots

<img width="400px" src="https://d.pr/f/qgNBlo.png">

**Comment by beafialho** [comment]
I've improved the alignment and replaced the icons for the correct ones from the WP Design Library. Uploaded the new icons [here](https://we.tl/t-NOU5K76jom).

<img width="713" alt="Captura de ecrã 2022-05-11, às 12 27 41" src="https://user-images.githubusercontent.com/65220155/167838779-aff76c43-ad01-4184-8fda-9b03f5e978b2.png">
