### ISSUE TITLE
Update block icons images

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-gutenberg#43]
There were some visible lines that were unintentional.

<img width="725" alt="Captura de ecrã 2022-05-10, às 10 33 03" src="https://user-images.githubusercontent.com/65220155/167597753-97f91686-49dc-4f7a-917c-eff493d798e7.png">

I exported them again and these seem to have no lines on my end: https://we.tl/t-1KMAmLQc20

**Comment by StevenDufresne** [comment]
Updated.
