### ISSUE TITLE
Fix “New to WordPress? No problem” headings.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-gutenberg#53]
“New to WordPress? No problem” is two headings, both with the same ID. It should be one heading, that will also fix the awkward line height:

<img width="673" alt="Screenshot 2023-03-27 at 9 29 01 AM" src="https://user-images.githubusercontent.com/1657336/227814915-f44cebe8-25f2-43c9-97a5-3189e743135d.png">

**Comment by FairyPenguin** [comment]
I can work on this.
