### ISSUE TITLE
Remove hand with book icon.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-gutenberg#54]
> Similarly, there’s an older illustration used around the helpful resources, that looks slightly out of place mostly because it isn’t used elsewhere on the page:

<img width="115" alt="Screenshot 2023-03-27 at 9 31 23 AM" src="https://user-images.githubusercontent.com/1657336/227815001-177afe4b-b9ea-4135-b9c1-791afa91f935.png">

**Comment by joaxaca** [comment]
Is this image to be removed?
If so, what about the DIV & column, remove them too?

**Comment by StevenDufresne** [comment]
Remove the icon in its entirety. Let's try to remove all empty html elements and clean up the html where applicable.
