### ISSUE TITLE
Allow the blog description to be updated in `wp-admin`

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-gutenberg#8]
It would be better if site admins could update the page description.

https://github.com/WordPress/wordpress.org/blob/142ef3c0c8a61c578feccb5d340e1752927cad8a/wordpress.org/public_html/wp-content/themes/pub/gutenberg/functions.php#L638

**Comment by dd32** [comment]
Given this theme is ultimately a one-page theme, perhaps we could use the Page Excerpt field as the site/page description? It would make things easier for the translation side too.
